permalink: /404.html


# theme: jekyll-theme-minimal

remote_theme: pages-themes/cayman@v0.2.0

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have onetitle: Octocat's homepage
- jekyll-seo-tag # for SEO optimiaztion

title: Ramit's homepage
description: Bookmark this to keep an eye on my project updates!

markdown: kramdown
